Develop
andrewbak37/java-explore-with-me pull request #1
Opened 2023-01-07 14:24 UTC by andrewbak37

2023-01-11 13:02 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/yandex/practicum/mainservice/user/controller/UserController.java
> +        return userService.createUser(userRequest);
Во все контроллеры нужно добавить логирование входных и выходных данных

2023-01-11 13:17 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/yandex/practicum/mainservice/user/controller/UserController.java
> +    }
При неверных входных данных желательно, чтобы сообщение об ошибке содержало информацию почему ошибка возникла

{
	"timestamp": 1673442085645,
	"status": 400,
	"error": "Bad Request",
	"path": "/admin/users"
}

2023-01-11 13:19 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/yandex/practicum/mainservice/user/controller/UserController.java
> +    public void deleteUser(@PathVariable("userId") Long userId) {
Если удалить несуществующего пользователя, то падает. На самом деле часто бывают задержи сети, бывают клиенты заново посылают запросы, делают ретраи. Не должно падать при повторном запросе. Можно вернуть Not Found
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.EmptyResultDataAccessException: No class ru.yandex.practicum.mainservice.user.model.User entity with id 1 exists!] with root cause
2023-01-11T13:17:11.014733800Z 
2023-01-11T13:17:11.014751600Z org.springframework.dao.EmptyResultDataAccessException: No class ru.yandex.practicum.mainservice.user.model.User entity with id 1 exists!

{
	"timestamp": 1673443031016,
	"status": 500,
	"error": "Internal Server Error",
	"path": "/admin/users/1"
}

2023-01-11 13:20 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/yandex/practicum/mainservice/user/dto/UserRequest.java
> +    @Email
по-моему еще должно быть поле login и birthday

2023-01-11 13:28 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/yandex/practicum/mainservice/event/service/EventServiceImpl.java
> +        return eventRepository.findEventsWithParams(params, pageable, true)
Попробуй переписать эти запросы так, чтобы делался всего один запрос. Сейчас на каждый найденный  event делаются еще селекты

2023-01-11 17:43 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/yandex/practicum/mainservice/event/service/EventServiceImpl.java
> +        }
Тут тоже три запроса, которые можно было бы сделать одним селектом.
Если есть желание, было бы здорово сократить количество селектов в таких случаях до одного

2023-01-11 17:54 UTC, EvgenyKoptubenko requested changes
Особых замечаний по коду нет. Код написан хорошо.
Если есть желание попробуй убрать множественные селекты и заменить их одним. Сделать один большой селект всегда быстрее, чем делать 4.
Так же нужно добавить логирование в контроллеры

2023-01-14 20:01 UTC, andrewbak37 commented on main-service/src/main/java/ru/yandex/practicum/mainservice/user/controller/UserController.java
> +        return userService.createUser(userRequest);
добавил в application.properties свойство `logging.level.org.springframework.web=DEBUG`, теперь в тестовом профиле запросы и ответы логируются

2023-01-14 20:01 UTC, andrewbak37 commented on main-service/src/main/java/ru/yandex/practicum/mainservice/user/controller/UserController.java
> +    }
добавил сообщение об ошибке

2023-01-14 20:02 UTC, andrewbak37 commented on main-service/src/main/java/ru/yandex/practicum/mainservice/user/controller/UserController.java
> +    public void deleteUser(@PathVariable("userId") Long userId) {
поправил на 404 вместо 500 в этом случае

2023-01-14 20:03 UTC, andrewbak37 commented on main-service/src/main/java/ru/yandex/practicum/mainservice/user/dto/UserRequest.java
> +    @Email
проверил по спецификации, логина и дня рождения нет

2023-01-14 20:04 UTC, andrewbak37 commented on main-service/src/main/java/ru/yandex/practicum/mainservice/event/service/EventServiceImpl.java
> +        return eventRepository.findEventsWithParams(params, pageable, true)
переделал, стало меньше запросов

2023-01-14 20:04 UTC, andrewbak37 commented on main-service/src/main/java/ru/yandex/practicum/mainservice/event/service/EventServiceImpl.java
> +        }
переделал на 1 селект

2023-01-15 17:32 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/yandex/practicum/mainservice/user/controller/UserController.java
> +        return userService.createUser(userRequest);
Если это тебе в дальнейшем позволит сделать метрики твоего приложения, создать графики работы приложения, то ок. Обычно на проде debug уровень выключен.

2023-01-15 17:33 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо. На будущее, например, когда будут спрашивать на собеседовании, то в проекте еще должно быть:
* 		Healthcheck (отдельный эндпоинт, который возвращает данные о том как себя чувствует приложение) - например описать как работает Spring Actuator
* 		На основе Healthcheck можно делать мониторинг, который будет периодически дергать этот эндпоинт и если что-то в healthcheck сломалось, то присылает алерты
* 		Так же в проекте должна быть документация, которая автоматически собирается - Docsify, например
* 		Так что должно быть отдельное приложение, которое собирает проект, создает артифакт и складывает его в хранилище. В Github тоже можно такое сделать.
* 		Во время код ревью должен подключаться Sonar для проверок.
* 		Во время пул реквеста так же должно подсчитываться покрытие кода тестами
* 		Приложение должно быть защищено, т.е. неавторизованные пользователи не должны иметь доступ к эндпоинтам. Почитай про OAUTH2
* 		В пул реквестах должно быть настроено минимальное количество апруверов, которые должны проверить и заапрувить пул реквест перед тем как его можно мерджить
* 		Все должно быть покрыто юнит тестами, так же должны быть написаны BDD тесты.
* 		Все, что не дает коду пройти в прод называется Quality Gates. К таким quality gates можно причислить: jUnit tests, BDD tests, Sonar, Pull Requests checks, code coverage, Catchpoint tests, Performance tests, Browserstack tests.
* 		Так же в приложении должен быть код, который создает инфраструктуру. Например, если ты хостишься в Amazon, то через Terraform нужно создать инфру.
* 		Дополнительный мониториг бизнес фич. У тебя должны быть графики о том как дела у приложения и у клиентов. И так же настроены алерты, если что-то пошло не так.

2023-01-16 08:36 UTC, merged